### PR TITLE
A very wacky solution

### PR DESCRIPTION
**Pull request by WitherCubes**
For #2

### CODE REVIEW

**Comment by bryant-the-coder** [comment]
heh. i think u should try asking the user which and which he or she wanna install.

**Comment by WitherCubes** [comment]
That is a good idea. I will work on it.

**Comment by bryant-the-coder** [comment]
yaya

**Comment by Manas140** [comment]
why is kitty.conf named paradise.conf, and alacritty.yml paradise.yml?

**Comment by bryant-the-coder** [comment]
ask him not me

**Comment by WitherCubes** [comment]
@Manas140 kitty.conf is named as paradise.conf, and alacritty.yml as paradise.yml because it can be sourced in the main config and easy to differenciate.

**Pull request merged**
